### ISSUE TITLE
an idea: font-smoothing

### ISSUE THREAD

**Issue by stevenvachon** [mateuszkocz/3l#9]
I know that it's WebKit only, but it still beats adding a vendor prefix:

``` css
.font-smoothing ()
{
    -webkit-font-smoothing: antialiased;
}
```
